### ISSUE TITLE
为什么会报getters undefined？

### ISSUE THREAD

**Issue by CloudWoR** [972784674t/vue-quasar-manage#2]
permission.js?3530:23 Uncaught (in promise) TypeError: Cannot read property 'getters' of undefined

**Comment by 972784674t** [comment]
请详细一些......

**Comment by CloudWoR** [comment]
sorry，我在quasar的electron项目中，引入了您的路由框架，在router/permission.js中，router.beforeEache()回调中，有一句：store.getters.getRoutes.length，控制台对这个地方报错：permission.js?3530:23 Uncaught (in promise) TypeError: Cannot read property 'getters' of undefined

**Comment by CloudWoR** [comment]
console.log(store.getters.getRouters.length)可以顺利打印出值。

**Comment by 972784674t** [comment]
console.log(store.getters.getRouters.length) 的打印结果是啥呢

**Comment by CloudWoR** [comment]
0

**Comment by CloudWoR** [comment]
`     const length = store.getters.getRoutes.length
    console.log('lenght: ', length) // 打印 0
    if (userRole && length) {
      next()
    } else {
      // 模拟不存在用户权限时，获取用户权限
      const userRole = sessionStorage.getItem('user_role')
      // 并根据权限设置对应的路由
      store.commit('SET_ROLES_AND_ROUTES', userRole)
      router.addRoutes(store.getters.getRoutes)
      // 如果 addRoutes 并未完成，路由守卫会再执行一次
      next({ ...to, replace: true })
    }`

**Comment by CloudWoR** [comment]
``    const length = store.getters.getRoutes.length
    console.log('lenght: ', length)
    if (userRole && length) {
      next()
    } else {
      // 模拟不存在用户权限时，获取用户权限
      const userRole = sessionStorage.getItem('user_role')
      // 并根据权限设置对应的路由
      store.commit('SET_ROLES_AND_ROUTES', userRole)
      router.addRoutes(store.getters.getRoutes)
      // 如果 addRoutes 并未完成，路由守卫会再执行一次
      next({ ...to, replace: true })
    }

**Comment by 972784674t** [comment]
咩看出啥端倪，方便发一下项目或是地址到邮箱吗 972784674@qq.com，如果可以的话。

**Comment by CloudWoR** [comment]
好的。

**Comment by 972784674t** [comment]
问题解决了，个人感觉原因是 node 环境和 浏览器环境 不同导致的，因此做了修改发邮箱给你作为参考，其实就是见招拆招，判断 store 是否被实例化，如果没有被实例化就先不执行调用。

当然也许还有更好的方法，如果你发现了，请告诉我

**Comment by CloudWoR** [comment]
貌似找到原因了，我开启了服务端渲染，所以state必须要以函数的方式返回。

**Comment by CloudWoR** [comment]
我熬了一个通宵，把兄弟你的这个项目和electron结合做了一个quasar + electron的项目，有没有兴趣？如果有，我push给你，一块儿把你这个项目做成electron版本的？

**Comment by 972784674t** [comment]
OK，来吧

**Comment by CloudWoR** [comment]
https://github.com/CloudWoR/quasar-electron.git

**Comment by CloudWoR** [comment]
只是大概整合了一下，还有一堆bug。
