### ISSUE TITLE
有计划提供一套代码规范吗？

### ISSUE THREAD

**Issue by 332lfgb6** [972784674t/vue-quasar-manage#3]
有的是驼峰命名法，有的是短线连接，看得我头都大了。。
![image](https://user-images.githubusercontent.com/51245335/111114504-4bebbe80-859e-11eb-8ade-e0fe5451b892.png)

**Comment by 972784674t** [comment]
不好意思哈，没注意到这个问题，之前是兴趣开发的，没想到效果还行，待会就弄哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月15日(周一) 下午2:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [972784674t/vue-quasar-manage] 有计划提供一套代码规范吗？ (#3)




 
有的是驼峰命名法，有的是短线连接，看得我头都大了。。

**Comment by 972784674t** [comment]
已经更新，就按照 vue 官网 =》 风格指南 来就可以啦

**Comment by 972784674t** [comment]
规范化

**Comment by 332lfgb6** [comment]
> 已经更新，就按照 vue 官网 =》 风格指南 来就可以啦

好
